### ISSUE TITLE
Menu working with SpringNavigator?

### ISSUE THREAD

**Issue by Ditscheridou** [KaesDingeling/Hybrid-Menu#43]
I am trying to integrate your awesome add-on to my application but i ran into an issue, that everytime when i want to navigate to my views, the menu disappears and i see only my views. Do you have any experience with SpringNavigators and your Add-On? 

This is the Init Sequence for the navigator: 
navigator.init(this, hybridMenu);
		navigator.addProvider(viewProvider);
		navigator.setErrorView(new ErrorView());
		setNavigator(navigator);

Best regards,
Jonas

**Comment by KaesDingeling** [comment]
Good evening, sir,

To follow your example, use the normal navigator of Vaadin. He's expecting on "navigator.init(this, 
naviContentRoot);" This means that everything you store in naviContentRoot will be deleted and replaced with the content of the page you want to navigate. This means that you have to change your tree structure as you design the DOM.

Let me give you an example of how the DOM is structured. Alternatively, I recommend you to have a look at the demo how this works, [here](https://github.com/KaesDingeling/Hybrid-Menu/tree/master/HybridMenu-demo/src/main/java/kaesdingeling/hybridmenu/demo) it is not necessary to initiate a navigator, because the menu does it.

![hybridmenuexample](https://user-images.githubusercontent.com/19664730/35244026-13797d34-ffbf-11e7-961d-0bce8055039c.png)
